#!/bin/bash
XENSTOREREAD=`which xenstore-read`
if [ -e $XENSTOREREAD ]; then
  NAME=`$XENSTOREREAD name`
  [ "$NAME" = "" ] && exit 0
  OLDNAME=`/bin/hostname -s`
  DOMAIN=`/bin/hostname -d`
  [ "$DOMAIN" = "" ] && exit 0

	/bin/sed -i "s/$OLDNAME/$NAME/g" /etc/hosts
  echo "$NAME.$DOMAIN" > /etc/hostname
	/bin/hostname -F /etc/hostname
fi
exit 0
